
# everything about data
data:
  # data_path: "/mnt/data/xyz.csv"
  # data_column: "raw_path"
  spatial_dims: 3
  input: 
    dir: "../B_cells"
    params:
      data_type: "tif"
    reader_params:
      dimension_order_out: "CZYX"
      C: [0]
      T: 0
  output:
    path: "../raw_predictions/B_cells"
    suffix: "pred_PP"
  dataloader_params:
    batch_size: 1
    num_workers: 1
  preprocess:
    - module_name: torchio
      func_name: ZNormalization
# model
model:
  category: FCN
  net: 
    module_name: monai.networks.nets
    func_name: UNet
    params:
      spatial_dims: 3
      in_channels: 1
      out_channels: 2
      channels: [16, 32, 64, 128, 256] 
      strides: [2, 2, 2, 2]
      num_res_units: 2
  sliding_window_params:
    dims_max: [1, 64, 256, 256]
    overlaps: [0, 8, 16, 16]
  ckpt:
    # checkpoint_path: /mnt/eternus/users/Sai/paired_data/segmentation_checkpoints/best_models_B_cells/unet_model_B_cells_rotation_scaling_1700_with_val_loss_0.11605121940374374_state.ckpt
    # checkpoint_path: /mnt/eternus/users/Sai/mmv_im2im_original/unet_model_2_B_cells_rotation_scaling_1700_with_val_loss_0.06112760677933693_state.ckpt
    checkpoint_path: /mnt/eternus/users/Sai/mmv_im2im_original/unet_model_4_previous_best_chkpt_1900_with_val_loss_0.07250680029392242_state.ckpt
    hparams_file: /mnt/eternus/users/Sai/mmv_im2im_dev/lightning_logs/version_46/hparams.yaml
# inference
run:
  gpus: 1
  precision: 16
